spring.application.name=api-veterinaria
server.port=8081

# Usamos H2 en memoria (No requiere instalar nada)
spring.datasource.url=jdbc:h2:mem:veterinariadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA / Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola web de H2 para ver los datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ruta de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html